# Generated by Django 5.2.6 on 2025-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_birth_day_user_birth_hour_user_birth_minute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
