# Generated by Django 5.2.6 on 2025-10-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="plan_type",
            field=models.CharField(default="free", max_length=50),
        ),
    ]
