# Generated by Django 5.2.7 on 2025-11-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_premium_user_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('tamil', 'Tamil'), ('hindi', 'Hindi')], default='english', max_length=20),
        ),
    ]
