# Generated by Django 5.2.7 on 2025-11-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
    ]
