# Generated by Django 5.2.7 on 2025-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
